language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install:
  - pecl install xmlrpc
  - composer self-update
  - composer install

install:
  - php -d memory_limit=-1 $(phpenv which composer) install --no-suggest --prefer-dist