language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install:
  - echo "extension=xmlrpc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install

install:
  - php -d memory_limit=-1 $(phpenv which composer) install --no-suggest --prefer-dist